defaults: &defaults
  apps_dir: <%= Rails.root.join('user_apps') %>

development:
  <<: *defaults

test:
  <<: *defaults

  domain_prefix: 'app'
  apps_dir: <%= Rails.root.join('spec', 'resources', 'user_apps') %>

production:
  <<: *defaults

  domain_prefix: 'app'
