# This is public config file, do NOT put any secrets here
defaults: &defaults
  apps_dir: <%= Rails.root.join('user_apps') %>

development:
  <<: *defaults

test:
  apps_dir: <%= Rails.root.join('spec', 'resources', 'user_apps') %>

production:
  <<: *defaults
